-- [[ INDEX ]]

-- 0. TEAM TABLE
	DROP TABLE TEAMS;
	DROP SEQUENCE SEQ_TEAMS_NO;

-- 1. USER TABLE
    DROP TABLE USER_INFO;
    DROP SEQUENCE SEQ_USER_NO;

-- 2. USER HISTORY TABLE
    DROP TABLE USER_HISTORY;
    DROP SEQUENCE SEQ_USER_HISTORY;

-- 3. USER_POLICY TABLE
    DROP TABLE USER_POLICY;

-- 4. USER_SESSION TABLE
	DROP TABLE USER_SESSION;


-- 5. REPORT TYPE TABLE
    DROP TABLE REPORT_TYPE;
    DROP SEQUENCE SEQ_REPORT_TYPE_NO;   

-- 6. REPORT VIOLATION TYPE TABLE
    DROP TABLE REPORT_VIOLATION_TYPE;

-- 7. REPORT TABLE
    DROP TABLE REPORT;
--0. STADIM_IMG TABLE
DROP TABLE  STADIUM_IMG;
--1. STADIUM TABLE
DROP TABLE STADIUM;
--2. MATCH_SCORE TABLE
DROP TABLE MATCH_SCORE;
--3. MATCH TABLE
DROP TABLE MATCH;

--4. HITTER_RECORD TABLE
DROP TABLE HITTER_RECORD;

--5. PITCHER_RECORD TABLE
DROP TABLE PITCHER_RECORD;
    


-- ========================================================================================================

-- 0. TEAM TABLE
CREATE TABLE TEAMS (
	"TEAM_NO" NUMBER PRIMARY KEY NOT NULL,
	"TEAM_NM" VARCHAR2(50) NOT NULL,
	"TEAM_CREATOR" VARCHAR2(50)	NOT NULL,
	"DIRECTOR" VARCHAR2(50) NOT NULL,
	"COMPANY" VARCHAR2(50) NOT NULL,
	"REGION" VARCHAR2(300) NOT NULL,
	"TEAM_DESCRIPTION"	VARCHAR2(4000)	NOT NULL,
	"TEAM_ST" CHAR(1) DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "TEAMS"."TEAM_NO" IS '구단 번호(SEQ_TEAM_NO)';
COMMENT ON COLUMN "TEAMS"."TEAM_NM" IS '구단 이름';
COMMENT ON COLUMN "TEAMS"."TEAM_CREATOR" IS '단장(구단 창단 신청자)';
COMMENT ON COLUMN "TEAMS"."DIRECTOR" IS '공증인(러닝메이트/감독/스카우터 중 1명)';
COMMENT ON COLUMN "TEAMS"."COMPANY" IS '모기업';
COMMENT ON COLUMN "TEAMS"."REGION" IS '광역 연고권/ 연고지';
COMMENT ON COLUMN "TEAMS"."TEAM_DESCRIPTION" IS '구단 설명';
COMMENT ON COLUMN "TEAMS"."TEAM_ST" IS '구단 상태(추가/제거)';

CREATE SEQUENCE SEQ_TEAMS_NO NOCACHE;

-- 1. USER TABLE
CREATE TABLE USER_INFO (
	"USER_NO" NUMBER PRIMARY KEY NOT NULL,
	"TEAM_NO" NUMBER CONSTRAINT FK_USER_TEAM_NO REFERENCES TEAMS(TEAM_NO) ON DELETE SET NULL,
	"USER_ID" VARCHAR2(20) CONSTRAINT UQ_USER_ID UNIQUE NOT NULL,
	"USER_PW" VARCHAR2(88) NOT NULL,
	"USER_EMAIL" VARCHAR2(100) CONSTRAINT UQ_USER_EMAIL UNIQUE NOT NULL,
	"USER_NAME"	VARCHAR2(48) NOT NULL,
	"USER_PHONE" CHAR(11),
	"USER_SNS" VARCHAR(100),
	"USER_BD" CHAR(8),
	"USER_ADDRESS" VARCHAR2(256),
	"USER_GENDER" CHAR(1),
	"USER_NATION" CHAR(2),
    "USER_IMG_ORIGIN" VARCHAR2(500),
    "USER_IMG_RENAME" VARCHAR2(500),
	"USER_AUTHORITY" CHAR(1) DEFAULT 'U' NOT NULL,
	"USER_ST" CHAR(1) DEFAULT 'G' NOT NULL,
	"CREATE_DT" DATE DEFAULT SYSDATE NOT NULL,
	"DELETE_DT" DATE,
	"FAIL_CNT" NUMBER DEFAULT 0
);

ALTER TABLE USER_INFO
ADD CONSTRAINT CK_USER_AUTHORITY CHECK(USER_AUTHORITY IN ('U', 'A'));

ALTER TABLE USER_INFO
ADD CONSTRAINT CK_USER_ST CHECK(USER_ST IN ('G', 'R', 'L'));

ALTER TABLE USER_INFO
ADD CONSTRAINT CK_USER_GENDER CHECK(USER_GENDER IN ('M', 'F'));

ALTER TABLE USER_INFO
ADD CONSTRAINT CK_USER_NATION CHECK(USER_NATION IN ('KO', 'FO'));

COMMENT ON COLUMN "USER_INFO"."USER_NO" IS '유저번호(SEQ_USER_NO)';
COMMENT ON COLUMN "USER_INFO"."TEAM_NO" IS '좋아요한 구단 번호(FK)';
COMMENT ON COLUMN "USER_INFO"."USER_ID" IS '유저 아이디(UNIQUE KEY)';
COMMENT ON COLUMN "USER_INFO"."USER_PW" IS '유저 비밀번호(SHA-512, BASE64)';
COMMENT ON COLUMN "USER_INFO"."USER_EMAIL" IS '유저 이메일';
COMMENT ON COLUMN "USER_INFO"."USER_NAME" IS '유저 이름 ( 한국어 3글자 제한)';
COMMENT ON COLUMN "USER_INFO"."USER_PHONE" IS '유저 전화번호(-없이)';
COMMENT ON COLUMN "USER_INFO"."USER_SNS" IS '유저 SNS 주소';
COMMENT ON COLUMN "USER_INFO"."USER_BD" IS 'YYYYMMDD  형식';
COMMENT ON COLUMN "USER_INFO"."USER_ADDRESS" IS 'XX시, XX동 (필수 시, 동)';
COMMENT ON COLUMN "USER_INFO"."USER_GENDER" IS '유저성별 (M or F)';
COMMENT ON COLUMN "USER_INFO"."USER_NATION" IS '유저 국적 KO(Korean), FO(Foreigner)';
COMMENT ON COLUMN "USER_INFO"."USER_AUTHORITY" IS '유저 권한 A(admin), U(user)';
COMMENT ON COLUMN "USER_INFO"."USER_ST" IS '유저 상태 G(granted), R(readOnly), L(Locked)';
COMMENT ON COLUMN "USER_INFO"."CREATE_DT" IS '유저 가입일';
COMMENT ON COLUMN "USER_INFO"."DELETE_DT" IS '유저 탈퇴일';
COMMENT ON COLUMN "USER_INFO"."USER_IMG_ORIGIN" IS '유저 프로필 이미지 원본';
COMMENT ON COLUMN "USER_INFO"."USER_IMG_RENAME" IS '유저 프로필 이미지 변경';
COMMENT ON COLUMN "USER_INFO"."FAIL_CNT" IS '로그인 실패 횟수';


CREATE SEQUENCE SEQ_USER_NO NOCACHE;

-- 2. USER HISTORY TABLE
CREATE TABLE USER_HISTORY (
	"HISTORY_NO" NUMBER	PRIMARY KEY NOT NULL,
	"USER_NO" NUMBER CONSTRAINT FK_USER_HISTORY_USER_NO REFERENCES USER_INFO(USER_NO) ON DELETE CASCADE NOT NULL,
	"LOGIN_DT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"LOGIN_AUTO" CHAR(1) DEFAULT 'N' NOT NULL
);

COMMENT ON COLUMN "USER_HISTORY"."HISTORY_NO" IS '히스토리번호(SEQ_HISOTRY_NO)';
COMMENT ON COLUMN "USER_HISTORY"."USER_NO" IS '유저번호(FK)';
COMMENT ON COLUMN "USER_HISTORY"."LOGIN_DT" IS '로그인시간';


ALTER TABLE USER_HISTORY
ADD CONSTRAINT CK_LOGIN_AUTO CHECK(LOGIN_AUTO IN ('N', 'Y'));

CREATE SEQUENCE SEQ_USER_HISTORY NOCACHE;


-- 3. USER_POLICY TABLE
CREATE TABLE USER_POLICY (
	"USER_NO" NUMBER CONSTRAINT FK_USER_POLICY_USER_NO REFERENCES USER_INFO(USER_NO) ON DELETE CASCADE NOT NULL,
	"AGREE_EMAIL" CHAR(1) DEFAULT 'N' NOT NULL,
	"AGREE_PHONE" CHAR(1) DEFAULT 'N' NOT NULL,
	"AGREE_ADDRESS" CHAR(1) DEFAULT 'N' NOT NULL
);

COMMENT ON COLUMN "USER_POLICY"."USER_NO" IS '유저번호(FK)';
COMMENT ON COLUMN "USER_POLICY"."AGREE_EMAIL" IS '이메일 정보동의 (N/Y)';
COMMENT ON COLUMN "USER_POLICY"."AGREE_PHONE" IS '전화번호 정보동의 (N/Y)';
COMMENT ON COLUMN "USER_POLICY"."AGREE_ADDRESS" IS '주소  정보동의 (N/Y)';

ALTER TABLE USER_POLICY
ADD CONSTRAINT CK_AGREE_EMAIL CHECK(AGREE_EMAIL IN ('N', 'Y'));

ALTER TABLE USER_POLICY
ADD CONSTRAINT CK_AGREE_PHONE CHECK(AGREE_PHONE IN ('N', 'Y'));

ALTER TABLE USER_POLICY
ADD CONSTRAINT CK_AGREE_ADDRESS CHECK(AGREE_ADDRESS IN ('N', 'Y'));

--4. USER SESSION TABLE
CREATE TABLE USER_SESSION (
    "USER_NO" NUMBER CONSTRAINT FK_USER_SESSION_NO REFERENCES USER_INFO ON DELETE CASCADE NOT NULL,
    "SESSION_UUID"	VARCHAR(64) NULL
);

COMMENT ON COLUMN "USER_SESSION"."USER_NO" IS '유저번호(SEQ_USER_NO)';
COMMENT ON COLUMN "USER_SESSION"."SESSION_UUID" IS '유저 UUID 토큰';

-- 5. REPORT TYPE TABLE

CREATE TABLE "REPORT_TYPE" (
	"REPORT_TYPE_NO" NUMBER PRIMARY KEY	NOT NULL,
	"REPORT_TYPE" VARCHAR2(48) NOT NULL
);

COMMENT ON COLUMN "REPORT_TYPE"."REPORT_TYPE_NO" IS '신고유형번호(SEQ_REPORT_TYPE_NO)';
COMMENT ON COLUMN "REPORT_TYPE"."REPORT_TYPE" IS '신고 유형 이름';

CREATE SEQUENCE SEQ_REPORT_TYPE_NO NOCACHE;

-- 6. REPORT VIOLATION TYPE TABLE
CREATE TABLE "REPORT_VIOLATION_TYPE" (
	"VIO_TYPE_NO" NUMBER PRIMARY KEY NOT NULL,
	"VIO_TYPE" VARCHAR2(48) NOT NULL
);

COMMENT ON COLUMN "REPORT_VIOLATION_TYPE"."VIO_TYPE_NO" IS '위반유형번호(SEQ_VIO_TYPE_NO)';
COMMENT ON COLUMN "REPORT_VIOLATION_TYPE"."VIO_TYPE" IS '위반 유형(성희롱/허위사실)';


-- 7. REPORT TABLE
CREATE TABLE REPORT (
	"REPORT_NO" NUMBER PRIMARY KEY NOT NULL,
	"USER_NO" NUMBER CONSTRAINT FK_REPORT_USER_NO REFERENCES USER_INFO(USER_NO) ON DELETE CASCADE NOT NULL,
	"REPORT_TYPE_NO" NUMBER CONSTRAINT FK_REPORT_REPORT_TYPE_NO REFERENCES REPORT_TYPE(REPORT_TYPE_NO) ON DELETE CASCADE NOT NULL,
	"TARTGET_NO" NUMBER NOT NULL,
	"VIO_TYPE_NO" NUMBER CONSTRAINT FK_REPORT_VIO_TYPE_NO REFERENCES REPORT_VIOLATION_TYPE(VIO_TYPE_NO) ON DELETE CASCADE NOT NULL,
	"REPORT_CONTENT" VARCHAR2(500) 	NOT NULL,
	"REPORT_DT"	DATE DEFAULT SYSDATE NOT NULL,
	"REPORT_ST"	CHAR(1)	DEFAULT 'P'	NOT NULL,

    CONSTRAINT UQ_REPORT_TYPE_NO_TARGET_NO UNIQUE(REPORT_TYPE_NO, TARTGET_NO)
);

ALTER TABLE REPORT
ADD CONSTRAINT CK_REPORT_ST CHECK(REPORT_ST IN ('A', 'C', 'P'));

COMMENT ON COLUMN "REPORT"."REPORT_NO" IS '신고번호(SEQ_REPORT_NO)';
COMMENT ON COLUMN "REPORT"."USER_NO" IS '유저번호(SEQ_USER_NO)';
COMMENT ON COLUMN "REPORT"."REPORT_TYPE_NO" IS '신고유형번호(SEQ_REPORT_TYPE_NO)';
COMMENT ON COLUMN "REPORT"."TARTGET_NO" IS '신고대상 번호';
COMMENT ON COLUMN "REPORT"."VIO_TYPE_NO" IS '위반유형번호(SEQ_VIO_TYPE_NO)';
COMMENT ON COLUMN "REPORT"."REPORT_CONTENT" IS '신고 내용';
COMMENT ON COLUMN "REPORT"."REPORT_DT" IS '신고일';
COMMENT ON COLUMN "REPORT"."REPORT_ST" IS '처리상태';

-- STADIUM 테이블
CREATE TABLE "STADIUM" (
	"STADIUM_NO"	NUMBER CONSTRAINT PK_STADIUM_STADIUM_NO PRIMARY KEY,
	"STADIUM_NAME"	VARCHAR2(100)		NOT NULL,
	"MAX_PEOPLE"	NUMBER		NOT NULL,
	"WIDTH_FILED"	NUMBER		NOT NULL,
	"STADIUM_PLACE"	VARCHAR2(4000)		NOT NULL
);
COMMENT ON COLUMN "STADIUM_IMG"."STADIUM_NO" IS '경기장번호';
COMMENT ON COLUMN "STADIUM_IMG"."IMG_ORIGINAL" IS '이미지원본명';
COMMENT ON COLUMN "STADIUM_IMG"."IMG_RENAME" IS '이미지변경명';
COMMENT ON COLUMN "STADIUM_IMG"."IMG_LEVEL" IS '이미지 레벨(위치)';

CREATE SEQUENCE SEQ_STADIUM_NO NOCACHE;

-- STADIUM_IMG 테이블
CREATE TABLE "STADIUM_IMG" (
	"STADIUM_NO"	NUMBER CONSTRAINT FK_STADIUM_IMG_STADIUM_NO REFERENCES STADIUM(STADIUM_NO) PRIMARY KEY,
	"IMG_ORIGINAL"	VARCHAR2(100)		NOT NULL,
	"IMG_RENAME"	VARCHAR2(100)		NOT NULL,
	"IMG_LEVEL"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "STADIUM"."STADIUM_NAME" IS '경기장 이름';
COMMENT ON COLUMN "STADIUM"."MAX_PEOPLE" IS '최대 수용 인원';
COMMENT ON COLUMN "STADIUM"."WIDTH_FILED" IS '경기장 면적';
COMMENT ON COLUMN "STADIUM"."STADIUM_PLACE" IS '경기장 주소';

--MATCH_SCORE 테이블
CREATE TABLE "MATCH_SCORE" (
	"SCORE_NO"	NUMBER CONSTRAINT PK_SCORE_NO PRIMARY KEY,
	"MATCH_NO"	NUMBER  NOT NULL,
	"TEAM_NO"	NUMBER NOT NULL,
	"HIT"	NUMBER		NOT NULL,
	"HOMERUN"	NUMBER		NOT NULL,
	"STKOUT"	NUMBER		NOT NULL,
	"STOLEBASE"	NUMBER		NOT NULL,
	"DOUBLEPLAY"	NUMBER		NOT NULL,
	"ERROR_SCORE"	NUMBER		NOT NULL,
    CONSTRAINT UQ_MATCH_SCORE_NO UNIQUE (MATCH_NO, TEAM_NO),
    CONSTRAINT FK_MATCH_SCORE_MATCH_NO REFERENCES MATCH(MATCH_NO, TEAM_NO)
);

COMMENT ON COLUMN "MATCH_SCORE"."SCORE_NO" IS '스코어번호';
COMMENT ON COLUMN "MATCH_SCORE"."MATCH_NO" IS '경기번호 + 구단 번호(PK)';
COMMENT ON COLUMN "MATCH_SCORE"."TEAM_NO" IS '경기번호 + 구단 번호(PK)';
COMMENT ON COLUMN "MATCH_SCORE"."HIT" IS '안타(개수)';
COMMENT ON COLUMN "MATCH_SCORE"."HOMERUN" IS '팀  홈런 (개수)';
COMMENT ON COLUMN "MATCH_SCORE"."STKOUT" IS '팀 삼진 (개수)';
COMMENT ON COLUMN "MATCH_SCORE"."STOLEBASE" IS '팀 도루 (개수)';
COMMENT ON COLUMN "MATCH_SCORE"."DOUBLEPLAY" IS '팀 병살 (개수)';
COMMENT ON COLUMN "MATCH_SCORE"."ERROR_SCORE" IS '팀 실책 (개수)';

-- HITTER_RECORED TABLE
CREATE TABLE "HITTER_RECORD" (
    "SCORE_NO"	NUMBER CONSTRAINT PK_HITTER_RECORD_SCORE_NO PRIMARY KEY,
    "PLAYER_NO"	NUMBER CONSTRAINT FK_HITTER_RECORD_PLAYER_NO REFERENCES PLAYER(PLAYER_NO) ON DELETE CASCADE  NOT NULL,
    "PLAYER_NAME"	VARCHAR2(40)		NOT NULL,
	"HIT_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"HIT"	NUMBER	DEFAULT 0	NOT NULL,
	"HOMERUN"	NUMBER	DEFAULT 0	NOT NULL,
	"RBI"	NUMBER	DEFAULT 0	NOT NULL,
	"STKOUT"	NUMBER	DEFAULT 0	NOT NULL,
	"DEADBALL"	NUMBER	DEFAULT 0	NOT NULL,
	"BAT_AVG"	NUMBER	DEFAULT 0	NOT NULL
       
);
 
COMMENT ON COLUMN "HITTER_RECORD"."SCORE_NO" IS '스코어번호';
COMMENT ON COLUMN "HITTER_RECORD"."PLAYER_NO" IS '선수 번호';
COMMENT ON COLUMN "HITTER_RECORD"."PLAYER_NAME" IS '선수이름';
COMMENT ON COLUMN "HITTER_RECORD"."HIT_COUNT" IS '타수';
COMMENT ON COLUMN "HITTER_RECORD"."HIT" IS '안타';
COMMENT ON COLUMN "HITTER_RECORD"."HOMERUN" IS '홈런';
COMMENT ON COLUMN "HITTER_RECORD"."RBI" IS '타점';
COMMENT ON COLUMN "HITTER_RECORD"."STKOUT" IS '삼진';
COMMENT ON COLUMN "HITTER_RECORD"."DEADBALL" IS '사사구';
COMMENT ON COLUMN "HITTER_RECORD"."BAT_AVG" IS '타율';


--PITCHER RECORD TABLE
CREATE TABLE "PITCHER_RECORD" (
	"SCORE_NO"	NUMBER CONSTRAINT PK_PITCTER_RECORD_SCORE_NO PRIMARY KEY,
	"PLAYER_NO"	NUMBER CONSTRAINT FK_PITCHER_RECORD_PLAYER_NO REFERENCES PLAYER(PLAYER_NO) ON DELETE CASCADE  NOT NULL,
	"PLAYER_NAME"	VARCHAR2(40)		NOT NULL,
	"INNING"	NUMBER	DEFAULT 0	NOT NULL,
	"PITCH_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"HITTED"	NUMBER	DEFAULT 0	NOT NULL,
	"HOMERUNED"	NUMBER	DEFAULT 0	NOT NULL,
	"SKTOUTED"	NUMBER	DEFAULT 0	NOT NULL,
	"DEADBALL"	NUMBER	DEFAULT 0	NOT NULL,
	"LOSS_SCORE"	NUMBER	DEFAULT 0	NOT NULL,
	"SELF_LOSE"	NUMBER	DEFAULT 0	NOT NULL,
	"ERA"	NUMBER	DEFAULT 0	NOT NULL,
	"WHIP"	NUMBER	DEFAULT 0	NOT NULL
    
);

COMMENT ON COLUMN "PITCHER_RECORD"."SCORE_NO" IS '스코어번호';
COMMENT ON COLUMN "PITCHER_RECORD"."PLAYER_NO" IS '선수 번호';
COMMENT ON COLUMN "PITCHER_RECORD"."PLAYER_NAME" IS '선수이름';
COMMENT ON COLUMN "PITCHER_RECORD"."INNING" IS '뛴 이닝';
COMMENT ON COLUMN "PITCHER_RECORD"."PITCH_COUNT" IS '투구 수';
COMMENT ON COLUMN "PITCHER_RECORD"."HITTED" IS '피안타';
COMMENT ON COLUMN "PITCHER_RECORD"."HOMERUNED" IS '피홈런';
COMMENT ON COLUMN "PITCHER_RECORD"."SKTOUTED" IS '탈삼진';
COMMENT ON COLUMN "PITCHER_RECORD"."DEADBALL" IS '사사구';
COMMENT ON COLUMN "PITCHER_RECORD"."LOSS_SCORE" IS '실점';
COMMENT ON COLUMN "PITCHER_RECORD"."SELF_LOSE" IS '자책';
COMMENT ON COLUMN "PITCHER_RECORD"."ERA" IS 'ERA';
COMMENT ON COLUMN "PITCHER_RECORD"."WHIP" IS 'WHIP';