-- 1. USER INFO 업데이트
UPDATE USER_INFO
SET USER_EMAIL = 'test@test.com'
WHERE USER_NO = 1;

-- 유저 권한 업데이트
UPDATE USER_INFO
SET USER_AUTHORITY = 'A', USER_ST = 'R'
WHERE USER_NO = 5;

-- 프로필 사진 업데이트
UPDATE USER_INFO
SET USER_IMG_ORIGIN = ? ,
    USER_IMG_RENAME = ?
WHERE USER_NO = ?;


COMMIT;
